/**
 * generated by Xtext 2.17.1
 */
package project.simple.ui.contentassist;

import project.simple.ui.contentassist.AbstractPDLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class PDLProposalProvider extends AbstractPDLProposalProvider {
}
