/*
 * generated by Xtext 2.17.1
 */
package project.simple.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import project.simple.pdl.ui.internal.PdlActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PDLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(PdlActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		PdlActivator activator = PdlActivator.getInstance();
		return activator != null ? activator.getInjector(PdlActivator.PROJECT_SIMPLE_PDL) : null;
	}

}
