/*
 * generated by Xtext 2.17.1
 */
package project.simple.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import project.simple.pdl.ui.internal.PdlActivator;

public class PDLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return PdlActivator.getInstance().getInjector("project.simple.PDL");
	}

}
