/**
 * generated by Xtext 2.17.1
 */
package project.simple.ide;

import project.simple.ide.AbstractPDLIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class PDLIdeModule extends AbstractPDLIdeModule {
}
