/**
 * generated by Xtext 2.17.1
 */
package project.simple.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import project.simple.ui.AbstractPDLUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class PDLUiModule extends AbstractPDLUiModule {
  public PDLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
