/*
 * generated by Xtext 2.17.1
 */
package project.simple.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPDLScopeProvider extends DelegatingScopeProvider {
}
