/**
 * generated by Xtext 2.17.1
 */
package project.simple.pDL.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.EObjectResolvingEList;
import org.eclipse.emf.ecore.util.InternalEList;

import project.simple.pDL.Guidance;
import project.simple.pDL.PDLPackage;
import project.simple.pDL.WorkDefinition;
import project.simple.pDL.WorkSequence;
import project.simple.pDL.parameter;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Work Definition</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link project.simple.pDL.impl.WorkDefinitionImpl#getName <em>Name</em>}</li>
 *   <li>{@link project.simple.pDL.impl.WorkDefinitionImpl#getLinksToPredecessors <em>Links To Predecessors</em>}</li>
 *   <li>{@link project.simple.pDL.impl.WorkDefinitionImpl#getLinksToSuccessors <em>Links To Successors</em>}</li>
 *   <li>{@link project.simple.pDL.impl.WorkDefinitionImpl#getGuidance <em>Guidance</em>}</li>
 *   <li>{@link project.simple.pDL.impl.WorkDefinitionImpl#getParameters <em>Parameters</em>}</li>
 * </ul>
 *
 * @generated
 */
public class WorkDefinitionImpl extends MinimalEObjectImpl.Container implements WorkDefinition
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getLinksToPredecessors() <em>Links To Predecessors</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLinksToPredecessors()
   * @generated
   * @ordered
   */
  protected EList<WorkSequence> linksToPredecessors;

  /**
   * The cached value of the '{@link #getLinksToSuccessors() <em>Links To Successors</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLinksToSuccessors()
   * @generated
   * @ordered
   */
  protected EList<WorkSequence> linksToSuccessors;

  /**
   * The cached value of the '{@link #getGuidance() <em>Guidance</em>}' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getGuidance()
   * @generated
   * @ordered
   */
  protected EList<Guidance> guidance;

  /**
   * The cached value of the '{@link #getParameters() <em>Parameters</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParameters()
   * @generated
   * @ordered
   */
  protected EList<parameter> parameters;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected WorkDefinitionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PDLPackage.Literals.WORK_DEFINITION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PDLPackage.WORK_DEFINITION__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<WorkSequence> getLinksToPredecessors()
  {
    if (linksToPredecessors == null)
    {
      linksToPredecessors = new EObjectResolvingEList<WorkSequence>(WorkSequence.class, this, PDLPackage.WORK_DEFINITION__LINKS_TO_PREDECESSORS);
    }
    return linksToPredecessors;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<WorkSequence> getLinksToSuccessors()
  {
    if (linksToSuccessors == null)
    {
      linksToSuccessors = new EObjectResolvingEList<WorkSequence>(WorkSequence.class, this, PDLPackage.WORK_DEFINITION__LINKS_TO_SUCCESSORS);
    }
    return linksToSuccessors;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Guidance> getGuidance()
  {
    if (guidance == null)
    {
      guidance = new EObjectResolvingEList<Guidance>(Guidance.class, this, PDLPackage.WORK_DEFINITION__GUIDANCE);
    }
    return guidance;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<parameter> getParameters()
  {
    if (parameters == null)
    {
      parameters = new EObjectContainmentEList<parameter>(parameter.class, this, PDLPackage.WORK_DEFINITION__PARAMETERS);
    }
    return parameters;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PDLPackage.WORK_DEFINITION__PARAMETERS:
        return ((InternalEList<?>)getParameters()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PDLPackage.WORK_DEFINITION__NAME:
        return getName();
      case PDLPackage.WORK_DEFINITION__LINKS_TO_PREDECESSORS:
        return getLinksToPredecessors();
      case PDLPackage.WORK_DEFINITION__LINKS_TO_SUCCESSORS:
        return getLinksToSuccessors();
      case PDLPackage.WORK_DEFINITION__GUIDANCE:
        return getGuidance();
      case PDLPackage.WORK_DEFINITION__PARAMETERS:
        return getParameters();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PDLPackage.WORK_DEFINITION__NAME:
        setName((String)newValue);
        return;
      case PDLPackage.WORK_DEFINITION__LINKS_TO_PREDECESSORS:
        getLinksToPredecessors().clear();
        getLinksToPredecessors().addAll((Collection<? extends WorkSequence>)newValue);
        return;
      case PDLPackage.WORK_DEFINITION__LINKS_TO_SUCCESSORS:
        getLinksToSuccessors().clear();
        getLinksToSuccessors().addAll((Collection<? extends WorkSequence>)newValue);
        return;
      case PDLPackage.WORK_DEFINITION__GUIDANCE:
        getGuidance().clear();
        getGuidance().addAll((Collection<? extends Guidance>)newValue);
        return;
      case PDLPackage.WORK_DEFINITION__PARAMETERS:
        getParameters().clear();
        getParameters().addAll((Collection<? extends parameter>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PDLPackage.WORK_DEFINITION__NAME:
        setName(NAME_EDEFAULT);
        return;
      case PDLPackage.WORK_DEFINITION__LINKS_TO_PREDECESSORS:
        getLinksToPredecessors().clear();
        return;
      case PDLPackage.WORK_DEFINITION__LINKS_TO_SUCCESSORS:
        getLinksToSuccessors().clear();
        return;
      case PDLPackage.WORK_DEFINITION__GUIDANCE:
        getGuidance().clear();
        return;
      case PDLPackage.WORK_DEFINITION__PARAMETERS:
        getParameters().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PDLPackage.WORK_DEFINITION__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case PDLPackage.WORK_DEFINITION__LINKS_TO_PREDECESSORS:
        return linksToPredecessors != null && !linksToPredecessors.isEmpty();
      case PDLPackage.WORK_DEFINITION__LINKS_TO_SUCCESSORS:
        return linksToSuccessors != null && !linksToSuccessors.isEmpty();
      case PDLPackage.WORK_DEFINITION__GUIDANCE:
        return guidance != null && !guidance.isEmpty();
      case PDLPackage.WORK_DEFINITION__PARAMETERS:
        return parameters != null && !parameters.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //WorkDefinitionImpl
