/*
 * generated by Xtext 2.17.1
 */
package project.simple


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class PDLRuntimeModule extends AbstractPDLRuntimeModule {
}
