/*
 * generated by Xtext 2.17.1
 */
package project.simple.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractEnumRuleElementFinder;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class PDLGrammarAccess extends AbstractGrammarElementFinder {
	
	public class ProcessElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "project.simple.PDL.Process");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cProcessKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cWorkDefinitionsKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cLeftCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cWorkDefinitionsAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cWorkDefinitionsWorkDefinitionParserRuleCall_5_0 = (RuleCall)cWorkDefinitionsAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCommaKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cWorkDefinitionsAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cWorkDefinitionsWorkDefinitionParserRuleCall_6_1_0 = (RuleCall)cWorkDefinitionsAssignment_6_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cWorkSequencesKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Assignment cWorkSequencesAssignment_8_2 = (Assignment)cGroup_8.eContents().get(2);
		private final RuleCall cWorkSequencesWorkSequenceParserRuleCall_8_2_0 = (RuleCall)cWorkSequencesAssignment_8_2.eContents().get(0);
		private final Group cGroup_8_3 = (Group)cGroup_8.eContents().get(3);
		private final Keyword cCommaKeyword_8_3_0 = (Keyword)cGroup_8_3.eContents().get(0);
		private final Assignment cWorkSequencesAssignment_8_3_1 = (Assignment)cGroup_8_3.eContents().get(1);
		private final RuleCall cWorkSequencesWorkSequenceParserRuleCall_8_3_1_0 = (RuleCall)cWorkSequencesAssignment_8_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8_4 = (Keyword)cGroup_8.eContents().get(4);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cGuidanceKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_9_1 = (Keyword)cGroup_9.eContents().get(1);
		private final Assignment cGuidanceAssignment_9_2 = (Assignment)cGroup_9.eContents().get(2);
		private final RuleCall cGuidanceGuidanceParserRuleCall_9_2_0 = (RuleCall)cGuidanceAssignment_9_2.eContents().get(0);
		private final Group cGroup_9_3 = (Group)cGroup_9.eContents().get(3);
		private final Keyword cCommaKeyword_9_3_0 = (Keyword)cGroup_9_3.eContents().get(0);
		private final Assignment cGuidanceAssignment_9_3_1 = (Assignment)cGroup_9_3.eContents().get(1);
		private final RuleCall cGuidanceGuidanceParserRuleCall_9_3_1_0 = (RuleCall)cGuidanceAssignment_9_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9_4 = (Keyword)cGroup_9.eContents().get(4);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final Keyword cResourceKeyword_10_0 = (Keyword)cGroup_10.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_10_1 = (Keyword)cGroup_10.eContents().get(1);
		private final Assignment cResourceAssignment_10_2 = (Assignment)cGroup_10.eContents().get(2);
		private final RuleCall cResourceResourceParserRuleCall_10_2_0 = (RuleCall)cResourceAssignment_10_2.eContents().get(0);
		private final Group cGroup_10_3 = (Group)cGroup_10.eContents().get(3);
		private final Keyword cCommaKeyword_10_3_0 = (Keyword)cGroup_10_3.eContents().get(0);
		private final Assignment cResourceAssignment_10_3_1 = (Assignment)cGroup_10_3.eContents().get(1);
		private final RuleCall cResourceResourceParserRuleCall_10_3_1_0 = (RuleCall)cResourceAssignment_10_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10_4 = (Keyword)cGroup_10.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_11 = (Keyword)cGroup.eContents().get(11);
		
		//Process:
		//	'Process'
		//	name=EString
		//	'{'
		//	'workDefinitions' '{' workDefinitions+=WorkDefinition ("," workDefinitions+=WorkDefinition)* '}' ('workSequences' '{'
		//	workSequences+=WorkSequence ("," workSequences+=WorkSequence)* '}')? ('guidance' '{' guidance+=Guidance (","
		//	guidance+=Guidance)* '}')? ('resource' '{' resource+=Resource ("," resource+=Resource)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Process' name=EString '{' 'workDefinitions' '{' workDefinitions+=WorkDefinition ("," workDefinitions+=WorkDefinition)*
		//'}' ('workSequences' '{' workSequences+=WorkSequence ("," workSequences+=WorkSequence)* '}')? ('guidance' '{'
		//guidance+=Guidance ("," guidance+=Guidance)* '}')? ('resource' '{' resource+=Resource ("," resource+=Resource)* '}')?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Process'
		public Keyword getProcessKeyword_0() { return cProcessKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//'workDefinitions'
		public Keyword getWorkDefinitionsKeyword_3() { return cWorkDefinitionsKeyword_3; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4() { return cLeftCurlyBracketKeyword_4; }
		
		//workDefinitions+=WorkDefinition
		public Assignment getWorkDefinitionsAssignment_5() { return cWorkDefinitionsAssignment_5; }
		
		//WorkDefinition
		public RuleCall getWorkDefinitionsWorkDefinitionParserRuleCall_5_0() { return cWorkDefinitionsWorkDefinitionParserRuleCall_5_0; }
		
		//("," workDefinitions+=WorkDefinition)*
		public Group getGroup_6() { return cGroup_6; }
		
		//","
		public Keyword getCommaKeyword_6_0() { return cCommaKeyword_6_0; }
		
		//workDefinitions+=WorkDefinition
		public Assignment getWorkDefinitionsAssignment_6_1() { return cWorkDefinitionsAssignment_6_1; }
		
		//WorkDefinition
		public RuleCall getWorkDefinitionsWorkDefinitionParserRuleCall_6_1_0() { return cWorkDefinitionsWorkDefinitionParserRuleCall_6_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
		
		//('workSequences' '{' workSequences+=WorkSequence ("," workSequences+=WorkSequence)* '}')?
		public Group getGroup_8() { return cGroup_8; }
		
		//'workSequences'
		public Keyword getWorkSequencesKeyword_8_0() { return cWorkSequencesKeyword_8_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_8_1() { return cLeftCurlyBracketKeyword_8_1; }
		
		//workSequences+=WorkSequence
		public Assignment getWorkSequencesAssignment_8_2() { return cWorkSequencesAssignment_8_2; }
		
		//WorkSequence
		public RuleCall getWorkSequencesWorkSequenceParserRuleCall_8_2_0() { return cWorkSequencesWorkSequenceParserRuleCall_8_2_0; }
		
		//("," workSequences+=WorkSequence)*
		public Group getGroup_8_3() { return cGroup_8_3; }
		
		//","
		public Keyword getCommaKeyword_8_3_0() { return cCommaKeyword_8_3_0; }
		
		//workSequences+=WorkSequence
		public Assignment getWorkSequencesAssignment_8_3_1() { return cWorkSequencesAssignment_8_3_1; }
		
		//WorkSequence
		public RuleCall getWorkSequencesWorkSequenceParserRuleCall_8_3_1_0() { return cWorkSequencesWorkSequenceParserRuleCall_8_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8_4() { return cRightCurlyBracketKeyword_8_4; }
		
		//('guidance' '{' guidance+=Guidance ("," guidance+=Guidance)* '}')?
		public Group getGroup_9() { return cGroup_9; }
		
		//'guidance'
		public Keyword getGuidanceKeyword_9_0() { return cGuidanceKeyword_9_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_9_1() { return cLeftCurlyBracketKeyword_9_1; }
		
		//guidance+=Guidance
		public Assignment getGuidanceAssignment_9_2() { return cGuidanceAssignment_9_2; }
		
		//Guidance
		public RuleCall getGuidanceGuidanceParserRuleCall_9_2_0() { return cGuidanceGuidanceParserRuleCall_9_2_0; }
		
		//("," guidance+=Guidance)*
		public Group getGroup_9_3() { return cGroup_9_3; }
		
		//","
		public Keyword getCommaKeyword_9_3_0() { return cCommaKeyword_9_3_0; }
		
		//guidance+=Guidance
		public Assignment getGuidanceAssignment_9_3_1() { return cGuidanceAssignment_9_3_1; }
		
		//Guidance
		public RuleCall getGuidanceGuidanceParserRuleCall_9_3_1_0() { return cGuidanceGuidanceParserRuleCall_9_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9_4() { return cRightCurlyBracketKeyword_9_4; }
		
		//('resource' '{' resource+=Resource ("," resource+=Resource)* '}')?
		public Group getGroup_10() { return cGroup_10; }
		
		//'resource'
		public Keyword getResourceKeyword_10_0() { return cResourceKeyword_10_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_10_1() { return cLeftCurlyBracketKeyword_10_1; }
		
		//resource+=Resource
		public Assignment getResourceAssignment_10_2() { return cResourceAssignment_10_2; }
		
		//Resource
		public RuleCall getResourceResourceParserRuleCall_10_2_0() { return cResourceResourceParserRuleCall_10_2_0; }
		
		//("," resource+=Resource)*
		public Group getGroup_10_3() { return cGroup_10_3; }
		
		//","
		public Keyword getCommaKeyword_10_3_0() { return cCommaKeyword_10_3_0; }
		
		//resource+=Resource
		public Assignment getResourceAssignment_10_3_1() { return cResourceAssignment_10_3_1; }
		
		//Resource
		public RuleCall getResourceResourceParserRuleCall_10_3_1_0() { return cResourceResourceParserRuleCall_10_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10_4() { return cRightCurlyBracketKeyword_10_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_11() { return cRightCurlyBracketKeyword_11; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "project.simple.PDL.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class WorkDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "project.simple.PDL.WorkDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cWorkDefinitionAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cWorkDefinitionKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cLinksToPredecessorsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cLinksToPredecessorsAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final CrossReference cLinksToPredecessorsWorkSequenceCrossReference_4_2_0 = (CrossReference)cLinksToPredecessorsAssignment_4_2.eContents().get(0);
		private final RuleCall cLinksToPredecessorsWorkSequenceEStringParserRuleCall_4_2_0_1 = (RuleCall)cLinksToPredecessorsWorkSequenceCrossReference_4_2_0.eContents().get(1);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cLinksToPredecessorsAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final CrossReference cLinksToPredecessorsWorkSequenceCrossReference_4_3_1_0 = (CrossReference)cLinksToPredecessorsAssignment_4_3_1.eContents().get(0);
		private final RuleCall cLinksToPredecessorsWorkSequenceEStringParserRuleCall_4_3_1_0_1 = (RuleCall)cLinksToPredecessorsWorkSequenceCrossReference_4_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cLinksToSuccessorsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cLinksToSuccessorsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final CrossReference cLinksToSuccessorsWorkSequenceCrossReference_5_2_0 = (CrossReference)cLinksToSuccessorsAssignment_5_2.eContents().get(0);
		private final RuleCall cLinksToSuccessorsWorkSequenceEStringParserRuleCall_5_2_0_1 = (RuleCall)cLinksToSuccessorsWorkSequenceCrossReference_5_2_0.eContents().get(1);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cLinksToSuccessorsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final CrossReference cLinksToSuccessorsWorkSequenceCrossReference_5_3_1_0 = (CrossReference)cLinksToSuccessorsAssignment_5_3_1.eContents().get(0);
		private final RuleCall cLinksToSuccessorsWorkSequenceEStringParserRuleCall_5_3_1_0_1 = (RuleCall)cLinksToSuccessorsWorkSequenceCrossReference_5_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cGuidanceKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cGuidanceAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final CrossReference cGuidanceGuidanceCrossReference_6_2_0 = (CrossReference)cGuidanceAssignment_6_2.eContents().get(0);
		private final RuleCall cGuidanceGuidanceEStringParserRuleCall_6_2_0_1 = (RuleCall)cGuidanceGuidanceCrossReference_6_2_0.eContents().get(1);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cGuidanceAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final CrossReference cGuidanceGuidanceCrossReference_6_3_1_0 = (CrossReference)cGuidanceAssignment_6_3_1.eContents().get(0);
		private final RuleCall cGuidanceGuidanceEStringParserRuleCall_6_3_1_0_1 = (RuleCall)cGuidanceGuidanceCrossReference_6_3_1_0.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cParametersKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_7_1 = (Keyword)cGroup_7.eContents().get(1);
		private final Assignment cParametersAssignment_7_2 = (Assignment)cGroup_7.eContents().get(2);
		private final RuleCall cParametersParameterParserRuleCall_7_2_0 = (RuleCall)cParametersAssignment_7_2.eContents().get(0);
		private final Group cGroup_7_3 = (Group)cGroup_7.eContents().get(3);
		private final Keyword cCommaKeyword_7_3_0 = (Keyword)cGroup_7_3.eContents().get(0);
		private final Assignment cParametersAssignment_7_3_1 = (Assignment)cGroup_7_3.eContents().get(1);
		private final RuleCall cParametersParameterParserRuleCall_7_3_1_0 = (RuleCall)cParametersAssignment_7_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7_4 = (Keyword)cGroup_7.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//WorkDefinition:
		//	{WorkDefinition}
		//	'WorkDefinition'
		//	name=EString
		//	'{' ('linksToPredecessors' '(' linksToPredecessors+=[WorkSequence|EString] (","
		//	linksToPredecessors+=[WorkSequence|EString])* ')')? ('linksToSuccessors' '(' linksToSuccessors+=[WorkSequence|EString]
		//	("," linksToSuccessors+=[WorkSequence|EString])* ')')? ('guidance' '(' guidance+=[Guidance|EString] (","
		//	guidance+=[Guidance|EString])* ')')? ('parameters' '{' parameters+=parameter ("," parameters+=parameter)* '}')?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{WorkDefinition} 'WorkDefinition' name=EString '{' ('linksToPredecessors' '('
		//linksToPredecessors+=[WorkSequence|EString] ("," linksToPredecessors+=[WorkSequence|EString])* ')')?
		//('linksToSuccessors' '(' linksToSuccessors+=[WorkSequence|EString] ("," linksToSuccessors+=[WorkSequence|EString])*
		//')')? ('guidance' '(' guidance+=[Guidance|EString] ("," guidance+=[Guidance|EString])* ')')? ('parameters' '{'
		//parameters+=parameter ("," parameters+=parameter)* '}')? '}'
		public Group getGroup() { return cGroup; }
		
		//{WorkDefinition}
		public Action getWorkDefinitionAction_0() { return cWorkDefinitionAction_0; }
		
		//'WorkDefinition'
		public Keyword getWorkDefinitionKeyword_1() { return cWorkDefinitionKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('linksToPredecessors' '(' linksToPredecessors+=[WorkSequence|EString] (","
		//linksToPredecessors+=[WorkSequence|EString])* ')')?
		public Group getGroup_4() { return cGroup_4; }
		
		//'linksToPredecessors'
		public Keyword getLinksToPredecessorsKeyword_4_0() { return cLinksToPredecessorsKeyword_4_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_4_1() { return cLeftParenthesisKeyword_4_1; }
		
		//linksToPredecessors+=[WorkSequence|EString]
		public Assignment getLinksToPredecessorsAssignment_4_2() { return cLinksToPredecessorsAssignment_4_2; }
		
		//[WorkSequence|EString]
		public CrossReference getLinksToPredecessorsWorkSequenceCrossReference_4_2_0() { return cLinksToPredecessorsWorkSequenceCrossReference_4_2_0; }
		
		//EString
		public RuleCall getLinksToPredecessorsWorkSequenceEStringParserRuleCall_4_2_0_1() { return cLinksToPredecessorsWorkSequenceEStringParserRuleCall_4_2_0_1; }
		
		//("," linksToPredecessors+=[WorkSequence|EString])*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//linksToPredecessors+=[WorkSequence|EString]
		public Assignment getLinksToPredecessorsAssignment_4_3_1() { return cLinksToPredecessorsAssignment_4_3_1; }
		
		//[WorkSequence|EString]
		public CrossReference getLinksToPredecessorsWorkSequenceCrossReference_4_3_1_0() { return cLinksToPredecessorsWorkSequenceCrossReference_4_3_1_0; }
		
		//EString
		public RuleCall getLinksToPredecessorsWorkSequenceEStringParserRuleCall_4_3_1_0_1() { return cLinksToPredecessorsWorkSequenceEStringParserRuleCall_4_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4_4() { return cRightParenthesisKeyword_4_4; }
		
		//('linksToSuccessors' '(' linksToSuccessors+=[WorkSequence|EString] ("," linksToSuccessors+=[WorkSequence|EString])*
		//')')?
		public Group getGroup_5() { return cGroup_5; }
		
		//'linksToSuccessors'
		public Keyword getLinksToSuccessorsKeyword_5_0() { return cLinksToSuccessorsKeyword_5_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_5_1() { return cLeftParenthesisKeyword_5_1; }
		
		//linksToSuccessors+=[WorkSequence|EString]
		public Assignment getLinksToSuccessorsAssignment_5_2() { return cLinksToSuccessorsAssignment_5_2; }
		
		//[WorkSequence|EString]
		public CrossReference getLinksToSuccessorsWorkSequenceCrossReference_5_2_0() { return cLinksToSuccessorsWorkSequenceCrossReference_5_2_0; }
		
		//EString
		public RuleCall getLinksToSuccessorsWorkSequenceEStringParserRuleCall_5_2_0_1() { return cLinksToSuccessorsWorkSequenceEStringParserRuleCall_5_2_0_1; }
		
		//("," linksToSuccessors+=[WorkSequence|EString])*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//linksToSuccessors+=[WorkSequence|EString]
		public Assignment getLinksToSuccessorsAssignment_5_3_1() { return cLinksToSuccessorsAssignment_5_3_1; }
		
		//[WorkSequence|EString]
		public CrossReference getLinksToSuccessorsWorkSequenceCrossReference_5_3_1_0() { return cLinksToSuccessorsWorkSequenceCrossReference_5_3_1_0; }
		
		//EString
		public RuleCall getLinksToSuccessorsWorkSequenceEStringParserRuleCall_5_3_1_0_1() { return cLinksToSuccessorsWorkSequenceEStringParserRuleCall_5_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_5_4() { return cRightParenthesisKeyword_5_4; }
		
		//('guidance' '(' guidance+=[Guidance|EString] ("," guidance+=[Guidance|EString])* ')')?
		public Group getGroup_6() { return cGroup_6; }
		
		//'guidance'
		public Keyword getGuidanceKeyword_6_0() { return cGuidanceKeyword_6_0; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_6_1() { return cLeftParenthesisKeyword_6_1; }
		
		//guidance+=[Guidance|EString]
		public Assignment getGuidanceAssignment_6_2() { return cGuidanceAssignment_6_2; }
		
		//[Guidance|EString]
		public CrossReference getGuidanceGuidanceCrossReference_6_2_0() { return cGuidanceGuidanceCrossReference_6_2_0; }
		
		//EString
		public RuleCall getGuidanceGuidanceEStringParserRuleCall_6_2_0_1() { return cGuidanceGuidanceEStringParserRuleCall_6_2_0_1; }
		
		//("," guidance+=[Guidance|EString])*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//guidance+=[Guidance|EString]
		public Assignment getGuidanceAssignment_6_3_1() { return cGuidanceAssignment_6_3_1; }
		
		//[Guidance|EString]
		public CrossReference getGuidanceGuidanceCrossReference_6_3_1_0() { return cGuidanceGuidanceCrossReference_6_3_1_0; }
		
		//EString
		public RuleCall getGuidanceGuidanceEStringParserRuleCall_6_3_1_0_1() { return cGuidanceGuidanceEStringParserRuleCall_6_3_1_0_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6_4() { return cRightParenthesisKeyword_6_4; }
		
		//('parameters' '{' parameters+=parameter ("," parameters+=parameter)* '}')?
		public Group getGroup_7() { return cGroup_7; }
		
		//'parameters'
		public Keyword getParametersKeyword_7_0() { return cParametersKeyword_7_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_7_1() { return cLeftCurlyBracketKeyword_7_1; }
		
		//parameters+=parameter
		public Assignment getParametersAssignment_7_2() { return cParametersAssignment_7_2; }
		
		//parameter
		public RuleCall getParametersParameterParserRuleCall_7_2_0() { return cParametersParameterParserRuleCall_7_2_0; }
		
		//("," parameters+=parameter)*
		public Group getGroup_7_3() { return cGroup_7_3; }
		
		//","
		public Keyword getCommaKeyword_7_3_0() { return cCommaKeyword_7_3_0; }
		
		//parameters+=parameter
		public Assignment getParametersAssignment_7_3_1() { return cParametersAssignment_7_3_1; }
		
		//parameter
		public RuleCall getParametersParameterParserRuleCall_7_3_1_0() { return cParametersParameterParserRuleCall_7_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7_4() { return cRightCurlyBracketKeyword_7_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class WorkSequenceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "project.simple.PDL.WorkSequence");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cWorkSequenceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLinkTypeKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cLinkTypeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cLinkTypeWorkSequenceTypeEnumRuleCall_3_0 = (RuleCall)cLinkTypeAssignment_3.eContents().get(0);
		private final Keyword cPredecessorKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cPredecessorAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cPredecessorWorkDefinitionCrossReference_5_0 = (CrossReference)cPredecessorAssignment_5.eContents().get(0);
		private final RuleCall cPredecessorWorkDefinitionEStringParserRuleCall_5_0_1 = (RuleCall)cPredecessorWorkDefinitionCrossReference_5_0.eContents().get(1);
		private final Keyword cSuccessorKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cSuccessorAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final CrossReference cSuccessorWorkDefinitionCrossReference_7_0 = (CrossReference)cSuccessorAssignment_7.eContents().get(0);
		private final RuleCall cSuccessorWorkDefinitionEStringParserRuleCall_7_0_1 = (RuleCall)cSuccessorWorkDefinitionCrossReference_7_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//WorkSequence:
		//	'WorkSequence'
		//	'{'
		//	'linkType' linkType=WorkSequenceType
		//	'predecessor' predecessor=[WorkDefinition|EString]
		//	'successor' successor=[WorkDefinition|EString]
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'WorkSequence' '{' 'linkType' linkType=WorkSequenceType 'predecessor' predecessor=[WorkDefinition|EString] 'successor'
		//successor=[WorkDefinition|EString] '}'
		public Group getGroup() { return cGroup; }
		
		//'WorkSequence'
		public Keyword getWorkSequenceKeyword_0() { return cWorkSequenceKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'linkType'
		public Keyword getLinkTypeKeyword_2() { return cLinkTypeKeyword_2; }
		
		//linkType=WorkSequenceType
		public Assignment getLinkTypeAssignment_3() { return cLinkTypeAssignment_3; }
		
		//WorkSequenceType
		public RuleCall getLinkTypeWorkSequenceTypeEnumRuleCall_3_0() { return cLinkTypeWorkSequenceTypeEnumRuleCall_3_0; }
		
		//'predecessor'
		public Keyword getPredecessorKeyword_4() { return cPredecessorKeyword_4; }
		
		//predecessor=[WorkDefinition|EString]
		public Assignment getPredecessorAssignment_5() { return cPredecessorAssignment_5; }
		
		//[WorkDefinition|EString]
		public CrossReference getPredecessorWorkDefinitionCrossReference_5_0() { return cPredecessorWorkDefinitionCrossReference_5_0; }
		
		//EString
		public RuleCall getPredecessorWorkDefinitionEStringParserRuleCall_5_0_1() { return cPredecessorWorkDefinitionEStringParserRuleCall_5_0_1; }
		
		//'successor'
		public Keyword getSuccessorKeyword_6() { return cSuccessorKeyword_6; }
		
		//successor=[WorkDefinition|EString]
		public Assignment getSuccessorAssignment_7() { return cSuccessorAssignment_7; }
		
		//[WorkDefinition|EString]
		public CrossReference getSuccessorWorkDefinitionCrossReference_7_0() { return cSuccessorWorkDefinitionCrossReference_7_0; }
		
		//EString
		public RuleCall getSuccessorWorkDefinitionEStringParserRuleCall_7_0_1() { return cSuccessorWorkDefinitionEStringParserRuleCall_7_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class GuidanceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "project.simple.PDL.Guidance");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cGuidanceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cDescriptionKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cDescriptionAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cDescriptionEStringParserRuleCall_3_0 = (RuleCall)cDescriptionAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Guidance:
		//	'Guidance'
		//	'{'
		//	'description' description=EString
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Guidance' '{' 'description' description=EString '}'
		public Group getGroup() { return cGroup; }
		
		//'Guidance'
		public Keyword getGuidanceKeyword_0() { return cGuidanceKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'description'
		public Keyword getDescriptionKeyword_2() { return cDescriptionKeyword_2; }
		
		//description=EString
		public Assignment getDescriptionAssignment_3() { return cDescriptionAssignment_3; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_3_0() { return cDescriptionEStringParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class ResourceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "project.simple.PDL.Resource");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cResourceAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cResourceKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cOccuranceNbKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cOccuranceNbAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cOccuranceNbEIntParserRuleCall_4_1_0 = (RuleCall)cOccuranceNbAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Resource:
		//	{Resource}
		//	'Resource'
		//	name=EString
		//	'{' ('OccuranceNb' OccuranceNb=EInt)?
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//{Resource} 'Resource' name=EString '{' ('OccuranceNb' OccuranceNb=EInt)? '}'
		public Group getGroup() { return cGroup; }
		
		//{Resource}
		public Action getResourceAction_0() { return cResourceAction_0; }
		
		//'Resource'
		public Keyword getResourceKeyword_1() { return cResourceKeyword_1; }
		
		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }
		
		//('OccuranceNb' OccuranceNb=EInt)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'OccuranceNb'
		public Keyword getOccuranceNbKeyword_4_0() { return cOccuranceNbKeyword_4_0; }
		
		//OccuranceNb=EInt
		public Assignment getOccuranceNbAssignment_4_1() { return cOccuranceNbAssignment_4_1; }
		
		//EInt
		public RuleCall getOccuranceNbEIntParserRuleCall_4_1_0() { return cOccuranceNbEIntParserRuleCall_4_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class ParameterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "project.simple.PDL.parameter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cParameterKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cQuantityKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cQuantityAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cQuantityEIntParserRuleCall_2_1_0 = (RuleCall)cQuantityAssignment_2_1.eContents().get(0);
		private final Keyword cResourceKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cResourceAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cResourceResourceCrossReference_4_0 = (CrossReference)cResourceAssignment_4.eContents().get(0);
		private final RuleCall cResourceResourceEStringParserRuleCall_4_0_1 = (RuleCall)cResourceResourceCrossReference_4_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//parameter:
		//	'parameter'
		//	'{' ('quantity' quantity=EInt)?
		//	'resource' resource=[Resource|EString]
		//	'}';
		@Override public ParserRule getRule() { return rule; }
		
		//'parameter' '{' ('quantity' quantity=EInt)? 'resource' resource=[Resource|EString] '}'
		public Group getGroup() { return cGroup; }
		
		//'parameter'
		public Keyword getParameterKeyword_0() { return cParameterKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('quantity' quantity=EInt)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'quantity'
		public Keyword getQuantityKeyword_2_0() { return cQuantityKeyword_2_0; }
		
		//quantity=EInt
		public Assignment getQuantityAssignment_2_1() { return cQuantityAssignment_2_1; }
		
		//EInt
		public RuleCall getQuantityEIntParserRuleCall_2_1_0() { return cQuantityEIntParserRuleCall_2_1_0; }
		
		//'resource'
		public Keyword getResourceKeyword_3() { return cResourceKeyword_3; }
		
		//resource=[Resource|EString]
		public Assignment getResourceAssignment_4() { return cResourceAssignment_4; }
		
		//[Resource|EString]
		public CrossReference getResourceResourceCrossReference_4_0() { return cResourceResourceCrossReference_4_0; }
		
		//EString
		public RuleCall getResourceResourceEStringParserRuleCall_4_0_1() { return cResourceResourceEStringParserRuleCall_4_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "project.simple.PDL.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt ecore::EInt:
		//	'-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	
	public class WorkSequenceTypeElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "project.simple.PDL.WorkSequenceType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cStartToStartEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cStartToStartStartToStartKeyword_0_0 = (Keyword)cStartToStartEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cFinishToStartEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cFinishToStartFinishToStartKeyword_1_0 = (Keyword)cFinishToStartEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cStartToFinishEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cStartToFinishStartToFinishKeyword_2_0 = (Keyword)cStartToFinishEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cFinishToFinishEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cFinishToFinishFinishToFinishKeyword_3_0 = (Keyword)cFinishToFinishEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum WorkSequenceType:
		//	startToStart | finishToStart | startToFinish | finishToFinish;
		public EnumRule getRule() { return rule; }
		
		//startToStart | finishToStart | startToFinish | finishToFinish
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//startToStart
		public EnumLiteralDeclaration getStartToStartEnumLiteralDeclaration_0() { return cStartToStartEnumLiteralDeclaration_0; }
		
		//'startToStart'
		public Keyword getStartToStartStartToStartKeyword_0_0() { return cStartToStartStartToStartKeyword_0_0; }
		
		//finishToStart
		public EnumLiteralDeclaration getFinishToStartEnumLiteralDeclaration_1() { return cFinishToStartEnumLiteralDeclaration_1; }
		
		//'finishToStart'
		public Keyword getFinishToStartFinishToStartKeyword_1_0() { return cFinishToStartFinishToStartKeyword_1_0; }
		
		//startToFinish
		public EnumLiteralDeclaration getStartToFinishEnumLiteralDeclaration_2() { return cStartToFinishEnumLiteralDeclaration_2; }
		
		//'startToFinish'
		public Keyword getStartToFinishStartToFinishKeyword_2_0() { return cStartToFinishStartToFinishKeyword_2_0; }
		
		//finishToFinish
		public EnumLiteralDeclaration getFinishToFinishEnumLiteralDeclaration_3() { return cFinishToFinishEnumLiteralDeclaration_3; }
		
		//'finishToFinish'
		public Keyword getFinishToFinishFinishToFinishKeyword_3_0() { return cFinishToFinishFinishToFinishKeyword_3_0; }
	}
	
	private final ProcessElements pProcess;
	private final EStringElements pEString;
	private final WorkDefinitionElements pWorkDefinition;
	private final WorkSequenceElements pWorkSequence;
	private final GuidanceElements pGuidance;
	private final ResourceElements pResource;
	private final ParameterElements pParameter;
	private final EIntElements pEInt;
	private final WorkSequenceTypeElements eWorkSequenceType;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public PDLGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pProcess = new ProcessElements();
		this.pEString = new EStringElements();
		this.pWorkDefinition = new WorkDefinitionElements();
		this.pWorkSequence = new WorkSequenceElements();
		this.pGuidance = new GuidanceElements();
		this.pResource = new ResourceElements();
		this.pParameter = new ParameterElements();
		this.pEInt = new EIntElements();
		this.eWorkSequenceType = new WorkSequenceTypeElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("project.simple.PDL".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Process:
	//	'Process'
	//	name=EString
	//	'{'
	//	'workDefinitions' '{' workDefinitions+=WorkDefinition ("," workDefinitions+=WorkDefinition)* '}' ('workSequences' '{'
	//	workSequences+=WorkSequence ("," workSequences+=WorkSequence)* '}')? ('guidance' '{' guidance+=Guidance (","
	//	guidance+=Guidance)* '}')? ('resource' '{' resource+=Resource ("," resource+=Resource)* '}')?
	//	'}';
	public ProcessElements getProcessAccess() {
		return pProcess;
	}
	
	public ParserRule getProcessRule() {
		return getProcessAccess().getRule();
	}
	
	//EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//WorkDefinition:
	//	{WorkDefinition}
	//	'WorkDefinition'
	//	name=EString
	//	'{' ('linksToPredecessors' '(' linksToPredecessors+=[WorkSequence|EString] (","
	//	linksToPredecessors+=[WorkSequence|EString])* ')')? ('linksToSuccessors' '(' linksToSuccessors+=[WorkSequence|EString]
	//	("," linksToSuccessors+=[WorkSequence|EString])* ')')? ('guidance' '(' guidance+=[Guidance|EString] (","
	//	guidance+=[Guidance|EString])* ')')? ('parameters' '{' parameters+=parameter ("," parameters+=parameter)* '}')?
	//	'}';
	public WorkDefinitionElements getWorkDefinitionAccess() {
		return pWorkDefinition;
	}
	
	public ParserRule getWorkDefinitionRule() {
		return getWorkDefinitionAccess().getRule();
	}
	
	//WorkSequence:
	//	'WorkSequence'
	//	'{'
	//	'linkType' linkType=WorkSequenceType
	//	'predecessor' predecessor=[WorkDefinition|EString]
	//	'successor' successor=[WorkDefinition|EString]
	//	'}';
	public WorkSequenceElements getWorkSequenceAccess() {
		return pWorkSequence;
	}
	
	public ParserRule getWorkSequenceRule() {
		return getWorkSequenceAccess().getRule();
	}
	
	//Guidance:
	//	'Guidance'
	//	'{'
	//	'description' description=EString
	//	'}';
	public GuidanceElements getGuidanceAccess() {
		return pGuidance;
	}
	
	public ParserRule getGuidanceRule() {
		return getGuidanceAccess().getRule();
	}
	
	//Resource:
	//	{Resource}
	//	'Resource'
	//	name=EString
	//	'{' ('OccuranceNb' OccuranceNb=EInt)?
	//	'}';
	public ResourceElements getResourceAccess() {
		return pResource;
	}
	
	public ParserRule getResourceRule() {
		return getResourceAccess().getRule();
	}
	
	//parameter:
	//	'parameter'
	//	'{' ('quantity' quantity=EInt)?
	//	'resource' resource=[Resource|EString]
	//	'}';
	public ParameterElements getParameterAccess() {
		return pParameter;
	}
	
	public ParserRule getParameterRule() {
		return getParameterAccess().getRule();
	}
	
	//EInt ecore::EInt:
	//	'-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//enum WorkSequenceType:
	//	startToStart | finishToStart | startToFinish | finishToFinish;
	public WorkSequenceTypeElements getWorkSequenceTypeAccess() {
		return eWorkSequenceType;
	}
	
	public EnumRule getWorkSequenceTypeRule() {
		return getWorkSequenceTypeAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
