/**
 * generated by Xtext 2.17.1
 */
package project.simple.validation;

import project.simple.validation.AbstractPDLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class PDLValidator extends AbstractPDLValidator {
}
