/**
 * generated by Xtext 2.17.1
 */
package project.simple.pDL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Process</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link project.simple.pDL.Process#getName <em>Name</em>}</li>
 *   <li>{@link project.simple.pDL.Process#getWorkDefinitions <em>Work Definitions</em>}</li>
 *   <li>{@link project.simple.pDL.Process#getWorkSequences <em>Work Sequences</em>}</li>
 *   <li>{@link project.simple.pDL.Process#getGuidance <em>Guidance</em>}</li>
 *   <li>{@link project.simple.pDL.Process#getResource <em>Resource</em>}</li>
 * </ul>
 *
 * @see project.simple.pDL.PDLPackage#getProcess()
 * @model
 * @generated
 */
public interface Process extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see project.simple.pDL.PDLPackage#getProcess_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link project.simple.pDL.Process#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Work Definitions</b></em>' containment reference list.
   * The list contents are of type {@link project.simple.pDL.WorkDefinition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Work Definitions</em>' containment reference list.
   * @see project.simple.pDL.PDLPackage#getProcess_WorkDefinitions()
   * @model containment="true"
   * @generated
   */
  EList<WorkDefinition> getWorkDefinitions();

  /**
   * Returns the value of the '<em><b>Work Sequences</b></em>' containment reference list.
   * The list contents are of type {@link project.simple.pDL.WorkSequence}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Work Sequences</em>' containment reference list.
   * @see project.simple.pDL.PDLPackage#getProcess_WorkSequences()
   * @model containment="true"
   * @generated
   */
  EList<WorkSequence> getWorkSequences();

  /**
   * Returns the value of the '<em><b>Guidance</b></em>' containment reference list.
   * The list contents are of type {@link project.simple.pDL.Guidance}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Guidance</em>' containment reference list.
   * @see project.simple.pDL.PDLPackage#getProcess_Guidance()
   * @model containment="true"
   * @generated
   */
  EList<Guidance> getGuidance();

  /**
   * Returns the value of the '<em><b>Resource</b></em>' containment reference list.
   * The list contents are of type {@link project.simple.pDL.Resource}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Resource</em>' containment reference list.
   * @see project.simple.pDL.PDLPackage#getProcess_Resource()
   * @model containment="true"
   * @generated
   */
  EList<Resource> getResource();

} // Process
