/**
 * generated by Xtext 2.17.1
 */
package project.simple.pDL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Resource</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link project.simple.pDL.Resource#getName <em>Name</em>}</li>
 *   <li>{@link project.simple.pDL.Resource#getOccuranceNb <em>Occurance Nb</em>}</li>
 * </ul>
 *
 * @see project.simple.pDL.PDLPackage#getResource()
 * @model
 * @generated
 */
public interface Resource extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see project.simple.pDL.PDLPackage#getResource_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link project.simple.pDL.Resource#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Occurance Nb</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Occurance Nb</em>' attribute.
   * @see #setOccuranceNb(int)
   * @see project.simple.pDL.PDLPackage#getResource_OccuranceNb()
   * @model
   * @generated
   */
  int getOccuranceNb();

  /**
   * Sets the value of the '{@link project.simple.pDL.Resource#getOccuranceNb <em>Occurance Nb</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Occurance Nb</em>' attribute.
   * @see #getOccuranceNb()
   * @generated
   */
  void setOccuranceNb(int value);

} // Resource
