/**
 * generated by Xtext 2.17.1
 */
package project.simple.pDL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Work Definition</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link project.simple.pDL.WorkDefinition#getName <em>Name</em>}</li>
 *   <li>{@link project.simple.pDL.WorkDefinition#getLinksToPredecessors <em>Links To Predecessors</em>}</li>
 *   <li>{@link project.simple.pDL.WorkDefinition#getLinksToSuccessors <em>Links To Successors</em>}</li>
 *   <li>{@link project.simple.pDL.WorkDefinition#getGuidance <em>Guidance</em>}</li>
 *   <li>{@link project.simple.pDL.WorkDefinition#getParameters <em>Parameters</em>}</li>
 * </ul>
 *
 * @see project.simple.pDL.PDLPackage#getWorkDefinition()
 * @model
 * @generated
 */
public interface WorkDefinition extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see project.simple.pDL.PDLPackage#getWorkDefinition_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link project.simple.pDL.WorkDefinition#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Links To Predecessors</b></em>' reference list.
   * The list contents are of type {@link project.simple.pDL.WorkSequence}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Links To Predecessors</em>' reference list.
   * @see project.simple.pDL.PDLPackage#getWorkDefinition_LinksToPredecessors()
   * @model
   * @generated
   */
  EList<WorkSequence> getLinksToPredecessors();

  /**
   * Returns the value of the '<em><b>Links To Successors</b></em>' reference list.
   * The list contents are of type {@link project.simple.pDL.WorkSequence}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Links To Successors</em>' reference list.
   * @see project.simple.pDL.PDLPackage#getWorkDefinition_LinksToSuccessors()
   * @model
   * @generated
   */
  EList<WorkSequence> getLinksToSuccessors();

  /**
   * Returns the value of the '<em><b>Guidance</b></em>' reference list.
   * The list contents are of type {@link project.simple.pDL.Guidance}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Guidance</em>' reference list.
   * @see project.simple.pDL.PDLPackage#getWorkDefinition_Guidance()
   * @model
   * @generated
   */
  EList<Guidance> getGuidance();

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' containment reference list.
   * The list contents are of type {@link project.simple.pDL.parameter}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' containment reference list.
   * @see project.simple.pDL.PDLPackage#getWorkDefinition_Parameters()
   * @model containment="true"
   * @generated
   */
  EList<parameter> getParameters();

} // WorkDefinition
