/**
 * generated by Xtext 2.17.1
 */
package project.simple;

import project.simple.AbstractPDLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class PDLRuntimeModule extends AbstractPDLRuntimeModule {
}
