/**
 * generated by Xtext 2.17.1
 */
package project.simple.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
@SuppressWarnings("all")
public class PDLOutlineTreeProvider extends DefaultOutlineTreeProvider {
}
